version: '3.0'

services:
  auth:
    build: ./auth
    restart: always
    ports:
      - "8081:8080"
    environment:
      - MONGO_URI=mongodb+srv://bankco:bankco2022@cluster0.3eyap.mongodb.net/mainDB?retryWrites=true&w=majority
      - EXPIRATION_TIME=2617920000


networks:
  web:
    driver: bridge
  mainnet: